var COLLISION_GROUPS = {};
COLLISION_GROUPS.BLOCK_SOLID = true;
COLLISION_GROUPS.BLOCK_ROTATE = true;
COLLISION_GROUPS.PLAYER_SOLID = true;
COLLISION_GROUPS.PLAYER_SENSOR = true;
module.exports = COLLISION_GROUPS;
